### ISSUE TITLE
Ability to tear down test resources

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector-test-harness#51]
See https://github.com/timberio/vector-test-harness/pull/44#discussion_r398208259.

Right now we do not have a way to manually tear down resources after running tests. Currently, we use CloudWatch alarms to automatically shut down idle instances, which works well for our current tests. But this starts to break down when we expand our types of tests. Such as long-running tests (https://github.com/timberio/vector-test-harness/pull/44), tests that spin up Kafka clusters, etc. We should think about a simple cleanup mechanism that can tear down _all_ test state after an idle period.

**Comment by jsirianni** [comment]
I am new to this project, but it seems to me that if terraform is used to create resources, it should also be leveraged for cleaning up. Is this not the case?

**Comment by jszwedko** [comment]
That is correct. This issue was actually closed by #52 which does use terraform to teardown the resources. Thanks for the bump!
