### ISSUE TITLE
Figure out a way to run different versions of vector with different configs

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector-test-harness#58]
We've made backwards incompatible changes to Vector's TOML file which means that we need a way to run older vector versions with a different config for some tests (e.g. `regex_parsing_performance`).

**Comment by Hoverbear** [comment]
Perhaps a "migrations" type system? Like SQL ORMs tend to use?

**Comment by blt** [comment]
This ticket's concerns are superseded by our soak testing infrastructure. That said, soak testing is purely forward facing and we may run into a similar problem in the future with that approach.
