### ISSUE TITLE
 Graph test-harness results somewhere

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector-test-harness#60]
It would be useful to plot the test-harness performance results somewhere.

Since these results are in Athena, AWS Quicksight could be an option. Alternatively, we execute a GA job to pull the results and publish them somewhere, maybe as a gh-pages branch on this repo?

**Comment by blt** [comment]
Now that we are actively working on #7638 the graphing location is Datadog, unless I'm much mistaken. This ticket might be considered superseded by #7955.
