### ISSUE TITLE
Use statistical analysis to identify regressions

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector-test-harness#61]
Currently we just compare the means and output +/- but it would good to be able to compare two runs for as statistical difference using a t-test.

We should enhance `bin/compare` (or maybe it is a separate script) to be able to perform this and exit non-zero if regressions occurred. We can then use this with https://github.com/timberio/vector/issues/5396 to send a message to discord if a regression is detected between two nightly runs.

Prior art: https://bheisler.github.io/criterion.rs/book/analysis.html

**Comment by blt** [comment]
This ticket's concerns are superseded by our soak testing infrastructure and its integration with Datadog.
