### ISSUE TITLE
Test comparisons are noisy

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector-test-harness#66]
While investigating a recent suspected regression, I discovered there wasn't actually one, but just a nightly that had an odd difference in throughput that went away when I reran a specific test case.

Some noise is to be expected given we are running on commodity AWS EC2 instances, but I am wondering if it would be worthwhile to attempt to reduce this to be able to more clearly identify regressions.

Some ideas:

* Run each benchmark case N times, on different hardware (i.e. running teardown after each one) and using the samples collected by all runs for comparison, rather than just the last one. This should reduce noisy neighbors.
* Run on dedicated hardware instead of virtual instances
* For comparisons, actually run the test cases once for each version being compared on the same EC2 instances

**Comment by blt** [comment]
This ticket's concerns are superseded by our soak testing infrastructure. We run with stable throughput inputs over long periods of time to avoid inherent random noise.
