### ISSUE TITLE
`Your query returned no results` error

### ISSUE THREAD

**Issue by ktff** [timberio/vector-test-harness#67]
When running `./bin/test` it throws three times the same error
```
Error: Your query returned no results. Please change your search criteria and try again.
```

Tried mixing up the flags to see if I'm passing some invalid argument to them but nothing changed.

Maybe it has something to do with the DynamoDB table in aws that I've created as it seamed to be needed for storing a lock, but I've not seen it documented in the setup.
[output.txt](https://github.com/timberio/vector-test-harness/files/5894469/output.txt)

**Comment by blt** [comment]
This ticket's concerns are superseded by our soak testing infrastructure. Any future iteration of test-harness work will use the basic infrastructure of that work.
