### ISSUE TITLE
Decide on integration benchmarking framework

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector-test-harness#68]
The Vector test harness was created alongside Vector by myself to compare Vector against alternatives. I am by no means a benchmarking expert and I am certain there are better ways to implement black box benchmarking. Before we begin work on https://github.com/timberio/vector/issues/6510 we should obtain consensus that improving the existing framework is the best path forward. If not, we should consider writing RFC that proposes a new approach.

**Comment by blt** [comment]
I believe this work is now completed. We have decided to address this with always-on soak testing.
